### ISSUE TITLE
Validation of calculations

### ISSUE THREAD

**Issue by MCilento93** [derekbraun/covid#1]
Hello,
have you validated the Rt calculations of this tool with results reported in weekely US reports?

I would like to understand the reliability of the results and furthermore the statistic reference adopted.
Thank you in advance 👍

**Comment by derekbraun** [comment]
I haven't validated my method. However, there are far better Rt calculators out there now.

I like this one: https://github.com/rtcovidlive/

**Comment by MCilento93** [comment]
Thank you for the relevant project you posted!
Actually it seems to me, from the "What's next" section of the jupyter-notebook, that Rt calculations are not so reliable and not necessarily tight to the results of national recognized institutions.
